; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = teensy

[env]
framework = arduino
lib_deps =
    https://github.com/bakercp/PacketSerial.git

#upload_port = /dev/ttyACM0
#monitor_port = /dev/ttyACM0
monitor_speed = 115200

[env:teensy]
platform = teensy
build_flags = -D TEENSY_OPT_SMALLEST_CODE
board = teensy41

[env:arduino_mega]
platform = atmelavr
board = megaatmega2560